const actionTypes = {
    START_TIMER: 'START_TIMER',
    STOP_TIMER: 'PAUSE_TIMER',
    CREATE_TASK: 'CREATE_TASK',
    UPDATE_ACTIVE_PROMODORO: 'UPDATE_ACTIVE_PROMODORO',
    CREATE_PROMODORO: 'CREATE_PROMODORO',
    FINISH_TASK: 'FINISH_TASK',
}

export default actionTypes;